### ISSUE TITLE
Handle errors occuring from duplicate timeslots in interviews

### ISSUE THREAD

**Issue by whtan99** [AY2122S2-CS2103-W17-4/tp#101]
Right now, it is possible to add 2 interviews at the exact same time, for 2 different roles, for the same candidate. We should do the error checking either in applicant or the interview class.

We might do it in the applicant class if we decide to link applicant with the interview, so that an applicant can see all his/her interviews in the next iteration.

**Comment by SethCKL** [comment]
Agreed on this issue.

I think it makes sense for applicant to contain information about all the interview that they have. 

I'm thinking of just storing all the Interview instances of an in an ArrayList which will be a new attribute of the applicant.

**Comment by likeabowx** [comment]
It makes sense for the applicant to be able to view all the interviews they have. I think that the list of interviews for the applicant can be obtained with a method like `getInterviewList()`. However, I am not sure if it is very inefficient to have to search through the interviews every time the method is called.

To take it one step further, we can even have like a `hasClashingInterview(dataTime)` method in applicant which can just check if the applicant already have an interview at that time.

**Comment by goalfix** [comment]
Great points guys! Let's KIV this issue for now, and wrap up version 1.2 first. If we have time, we can implement this else we can do it in the next iteration!

**Comment by goalfix** [comment]
Alright, given that the team has discussed that I bi-directional relationship complicates matters, I will look into implementing it on the interview component. Thanks!
