### ISSUE TITLE
Edit sample data for Applicants

### ISSUE THREAD

**Issue by YiHern-Lee** [AY2122S2-CS2103-W17-4/tp#178]
Currently the tags for the applicants in the sample data do not really make sense in the context of our application. 

![image](https://user-images.githubusercontent.com/77192850/160881711-a8f5d64e-d57f-44fc-a93c-35ba37224204.png)

E.g. "friends" and "colleagues" do not make sense for potential hirees.

**Comment by likeabowx** [comment]
Can edit for positions as well
