### ISSUE TITLE
[PE-D] Unexpected error with help command

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103-W17-4/tp#251]
# Problem
When trying to execute `help` to search for the usage of `help`, in other words entering `help help`, an error occurs.

# Steps to reproduce
Enter the command: `help help`

# Expected
A popup window/tab is opened containing information about the `help` command.

# Actual behavior
Error message show: `Sorry, we don't have this command. Please try again.`

# Screenshot

![image.png](https://raw.githubusercontent.com/DavidTan0527/ped/main/files/25eb4f84-ff51-44c2-afc8-3daafa61cc60.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: DavidTan0527/ped#9

**Comment by likeabowx** [comment]
@khoahre123 do you think we need a `help help` command to provide help for `help`?

Note: I don't think it makes sense since you already know there is a `help` command to type `help help`

**Comment by khoahre123** [comment]
> @khoahre123 do you think we need a `help help` command to provide help for `help`?
> 
> Note: I don't think it makes sense since you already know there is a `help` command to type `help help`

I think I can create a joke help if someone actually typing help help
