### ISSUE TITLE
[User Guide] Inconsistent titles

### ISSUE THREAD

**Issue by likeabowx** [AY2122S2-CS2103-W17-4/tp#318]
<img width="863" alt="Screenshot 2022-04-10 at 5 26 38 PM" src="https://user-images.githubusercontent.com/68813082/162611767-552367e3-5dd4-4aff-adc4-4e18e500ebd8.png">

**Comment by SethCKL** [comment]
Fixed by @YiHern-Lee in https://github.com/AY2122S2-CS2103-W17-4/tp/pull/344
